---
abstract: 'a modular policy daemon for postfix'
author:
  - 'Markus Benning <ich@markusbenning.de>'
build_requires:
  File::Find: 0
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-MtPolicyd
requires:
  BerkeleyDB: 0
  BerkeleyDB::Hash: 0
  Cache::Memcached: 0
  Config::General: 0
  DBI: 0
  Data::Dumper: 0
  Geo::IP: 0
  Getopt::Long: 0
  HTTP::Request::Common: 0
  IO::Handle: 0
  IO::Socket::INET: 0
  IO::Socket::UNIX: 0
  JSON: 0
  LWP::UserAgent: 0
  Mail::RBL: 0
  Mail::SPF: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Getopt: 0
  MooseX::Role::Parameterized: 0
  Net::Server::PreFork: 0
  Tie::IxHash: 0
  Time::HiRes: 0
  Time::Piece::MySQL: 0
  Time::Seconds: 0
  base: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mail-MtPolicyd
  repository: https://github.com/benningm/mtpolicyd
version: 1.13
